### ISSUE TITLE
bdcl not working

### ISSUE THREAD

**Issue by espy02** [daot/bcdl#1]
When I open bcdl, it opens up a command prompt with the letters "bcdl" on it, but then it closes itself. I thought I had to fill up the config.yaml file but even after doing that it still closes on it own.

**Comment by daot** [comment]
This is a command line utility, so you have to run it from the command prompt.

Go to the folder you have the binary in (.exe) and open the command prompt by holding your shift key, right clicking in the folder, and selecting "Open Powershell window here" or "Open CMD window here".
From the command line, all you have to do is run "bcdl.exe [link]" to run the program.

Hope this helps!
