### ISSUE TITLE
Artists with dash in URL not downloading

### ISSUE THREAD

**Issue by ewkytpmv** [daot/bcdl#3]
(sax music starts)

My name is Jones. Detective Jones. I hunt bugs for a living. 

First off, excellent piece of software, love that I can grab descriptions and reviews for every album. Sadly, I'm unable to download albums from artists with dashes in their ID. Afraid we've got a bug on our hands.

I went to grab albums from this page here:
`https://dream-catalogue.bandcamp.com/music`
I thought everything was going well until I noticed that bcdl had cut off the first part of the URL without the dash, and was downloading from _catalogue_.bandcamp.com instead:

```
==> https://dream-catalogue.bandcamp.com/music
>>> Getting links from Artist Page (May take a while)

==> https://catalogue.bandcamp.com/album/high-grey-effective
### Paid

==> https://catalogue.bandcamp.com/album/6-tracks-demo
--- 6 tracks demo by Catalogue
>>> fsig=70ae2e80338d0058c8c041867a88f928 id=853020959 ts=1626092884.0
==> https://popplers5.bandcamp.com/download/album?enc=flac&fsig=89761aeba0ebdd16ed80f38094bdbe5b&id=853020959&ts=1626092884.4146229350
 134.08 MiB / 230.54 MiB [======================================>---------------------------]  58.16% 2.23 MiB/s 00m43s
```

I tried putting the link in quotes but nothing changed so I decided to try a single album from the page in a text file with the -b option. Despite being free, bcdl reported it being paid and refused to download it:

```
==> https://dream-catalogue.bandcamp.com/album/flightwave-passions-vol-2
### Paid
```

To make sure this wasn't an issue unique to this specific page I quickly found another random artist page with a dash: 
`https://isistheband-ipecac.bandcamp.com/music`
This time, likely because ipecac.bandcamp.com doesn't have any releases, bcdl output this:

```
==> https://isistheband-ipecac.bandcamp.com/music
>>> Getting links from Artist Page (May take a while)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x71b0fa]

goroutine 1 [running]:
github.com/deepsheth/soup.findAllofem.func1(0x0, 0xc000033160, 0x1, 0x1, 0x868100)
        C:/Users/toad/go/src/github.com/deepsheth/soup/soup.go:529 +0x41a
github.com/deepsheth/soup.findAllofem(0x0, 0xc000033160, 0x1, 0x1, 0x820700, 0xc000168486, 0x0, 0x8)
        C:/Users/toad/go/src/github.com/deepsheth/soup/soup.go:533 +0xf7
github.com/deepsheth/soup.Root.FindAll(0x0, 0x0, 0x0, 0x952b00, 0xc0000049c0, 0xc000033160, 0x1, 0x1, 0x0, 0x0, ...)
        C:/Users/toad/go/src/github.com/deepsheth/soup/soup.go:278 +0x73
main.artistPageLinkGen(0xc000168480, 0x1b)
        D:/Web/Programming/c/bcdl.go:553 +0x35d
main.availAndDownload(0xc000168480, 0x21)
        D:/Web/Programming/c/bcdl.go:701 +0x231
main.get(0xc00000c270, 0x2d)
        D:/Web/Programming/c/bcdl.go:733 +0x296
main.main()
        D:/Web/Programming/c/bcdl.go:865 +0xfe0 
```

Until this bug is fixed I'm afraid this case is still open.

(sax music finale)

**Comment by daot** [comment]
ooh this is interesting. I'll look into it

**Comment by daot** [comment]
should be fixed in the latest commit. please tell me if all goes well :)

**Comment by ewkytpmv** [comment]
update: it's back
