### ISSUE TITLE
bcdl incompatible with custom domains

### ISSUE THREAD

**Issue by koocieyu** [daot/bcdl#6]
Some artists use custom domains for their bandcamp page but bcdl is not able to handle them. ([example](https://3six.net/album/indigo-expanse))

![image](https://user-images.githubusercontent.com/26856087/140631347-eb23a548-aed1-488a-9a89-800956cbab5c.png)

**Comment by steamyalt** [comment]
Can confirm.
This is caused by the validateLink function checking if its a *.bandcamp.com link.
Fixing this would require a more sophisticated validation function

**Comment by daot** [comment]
should be fixed! a while later haha
